services:
  - type: web
    name: Portfolio-V2
    env: static
    buildCommand: cd Frontend && npm ci && npm run build
    staticPublishPath: Frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html