services:
  - type: web
    name: portfolio-v2
    env: static
    buildCommand: cd src/Frontend && npm ci && npm run build
    staticPublishPath: ./src/Frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html